<?php

// "3" DIGIT THREE
return new Zete7\NumberLikeString\CharacterSet("\u{0033}", array(
    "\u{01B7}", // "Ʒ" LATIN CAPITAL LETTER EZH
    "\u{021C}", // "Ȝ" LATIN CAPITAL LETTER YOGH
    "\u{021D}", // "ȝ" LATIN SMALL LETTER YOGH
    "\u{0292}", // "ʒ" LATIN SMALL LETTER EZH
    "\u{0417}", // "З" CYRILLIC CAPITAL LETTER ZE
    "\u{0437}", // "з" CYRILLIC SMALL LETTER ZE
    "\u{04E0}", // "Ӡ" CYRILLIC CAPITAL LETTER ABKHASIAN DZE
    "\u{04E1}", // "ӡ" CYRILLIC SMALL LETTER ABKHASIAN DZE
    "\u{0545}", // "Յ" ARMENIAN CAPITAL LETTER YI
    "\u{0604}", // "؄" ARABIC SIGN SAMVAT
    "\u{1012}", // "ဒ" MYANMAR LETTER DA
    "\u{10D5}", // "ვ" GEORGIAN LETTER VIN
    "\u{10D9}", // "კ" GEORGIAN LETTER KAN
    "\u{10DE}", // "პ" GEORGIAN LETTER PAR
    "\u{10F3}", // "ჳ" GEORGIAN LETTER WE
    "\u{1C95}", // "Ვ" GEORGIAN MTAVRULI CAPITAL LETTER VIN
    "\u{1C99}", // "Კ" GEORGIAN MTAVRULI CAPITAL LETTER KAN
    "\u{1C9E}", // "Პ" GEORGIAN MTAVRULI CAPITAL LETTER PAR
    "\u{1CB3}", // "Ჳ" GEORGIAN MTAVRULI CAPITAL LETTER WE
    "\u{308D}", // "ろ" HIRAGANA LETTER RO
));
